### ISSUE TITLE
Invalid config file documentation

### ISSUE THREAD

**Issue by izogfif** [ffflorian/jszip-cli#1094]
When I try to create a ZIP archive with explicit entries listed in `.jsziprc.json` file, I get an error:

```
$ npx jszip-cli -c  /full-path-to-file/.jsziprc.json
C:\Users\username\AppData\Local\npm-cache\_npx\5f6822ab1bb27a15\node_modules\jszip-cli\index.js:37
    filesAndDirs.forEach(f => fs.stat(f.name || f, (err, stats) => {
```
Error happens in function `startProcessing`. If you trace the call stack, you can see this code:
```
    .action(function(filesAndDirs, options) {
        if (options.config) {
            jsonfile.readFile(filesAndDirs[0], (err, obj) => {
                if (!err) {
                    startProcessing(obj.entities, Object.assign({}, options, obj.options));
                } else {
                    console.error(`unable to read config file ${options.config}`);
                }
            });
```
Documentation states `entries`, but code expects `entities` instead of `entries` in `.jsziprc.json` file.
Same with `output`: documentation states `outputEntry`, but the code expects `options.output`:
```
            const finalize = () => compress(zip, options.output || `${filesAndDirs[0]}.zip`, options.level);
```

So the valid .jsziprc.json file must be
```
{
  "compressionLevel": 9,
  "dereferenceLinks": true,
  "entities": [
    "dist"
  ],
  "force": true,
  "ignoreEntries": [
    "*.map"
  ],
  "mode": "add",
  "options": {
    "output": "dist.zip"
  },
  "quiet": false,
  "verbose": false
}
```

instead of 
```
{
  "compressionLevel": 9,
  "dereferenceLinks": true,
  "entries": [
    "dist"
  ],
  "force": true,
  "ignoreEntries": [
    "*.map"
  ],
  "mode": "add",
  "outputEntry": "dist.zip",
  "quiet": false,
  "verbose": false
}
```

`"compressionLevel": 9` and `"compressionLevel": 1` yield in archive of the same size when compressing textual data, so I'm not sure whether this option is located in a correct level.

**Comment by ffflorian** [comment]
Hi @izogfif,
when running `npx jszip-cli`, you are running @Le0Michine's version of `jszip-cli` (https://www.npmjs.com/package/jszip-cli). Can you please try again by running `npx @ffflorian/jszip-cli` instead?

**Comment by izogfif** [comment]
You're correct. I wonder how I found _this_ repository on GitHub when I was looking for `jszip-cli` sources to report an error...
There are no problems when I run `npx @ffflorian/jszip-cli`. I don't even have to use `-c` flag to provide a name for `.jsziprc.json` file - it's detected automatically.
Issue closed: not an issue.

**Comment by ffflorian** [comment]
> Maybe it's worth mentioning `npx @ffflorian/jszip-cli` command in "Usage" section of readme file for those like me.

I'll do that! Glad to see it's working :)
