### ISSUE TITLE
Error: entry.replaceAll is not a function

### ISSUE THREAD

**Issue by jjohnson1994** [ffflorian/jszip-cli#879]
Hello,

I'm getting this error running jszip-cli as part of a deployment pipeline.
```
Error: entry.replaceAll is not a function
```

The pipeline uses Node version 14 but `replaceAll` isn't supported by Node versions > 15.

It looks like this is the commit that introduces the error https://github.com/ffflorian/jszip-cli/commit/6020351e8461c93a448e6a74670c367844e4c235

Would it be possible to replace with something like `new RegExp(entry.replace(/\*/g, '.*'))` instead? I think that will have the same result and not break any compatibility

**Comment by ffflorian** [comment]
Hey @jjohnson1994, good idea. Could you create a PR? 🙂

**Comment by ffflorian** [comment]
Fixed with 9b3018e1ce33f75711df36a08795f1455e55816a.
